### ISSUE TITLE
Installed ncbi-vdb package cannot be found by sratools

### ISSUE THREAD

**Issue by vradore** [ncbi/ncbi-vdb#10]
I just installed ncbi-vdb 2.8.0. Everything was found in the ./configure step and installation completed without warning or error. 
When I ran ./configure for sratools, however, no ncbi-vdb package was found.

I tried many things people shared online, mainly specifying locations in the ./configure step, but couldn't solve the issue. I started to think whether ncbi-vdb was properly installed.  I checked the possible include directory, since ./configure for sratools showed that there was no ncbi-vdb "includes".

$ ls /usr/local/ncbi/ncbi-vdb/include/ncbi-vdb/
   NGS.hpp

It is strange because there is only one file "NGS.hpp" found in the include directory. Can anyone tell me whether this is normal or whether the include files were properly installed?

**Comment by kwrodarmer** [comment]
I don't see that you mention installation of the ngs package. If it's not installed, that is likely to be the problem.

If you haven't already seen it, here are instructions for building ncbi-vdb:
[https://github.com/ncbi/ncbi-vdb/wiki/Building-and-Installing-from-Source](https://github.com/ncbi/ncbi-vdb/wiki/Building-and-Installing-from-Source)

**Comment by vradore** [comment]
I did install ngs before ncbi-vdb.

**Comment by kwrodarmer** [comment]
Alright - I'll assign an engineer to help you!

**Comment by vradore** [comment]
I made a folder ncbi and downloaded all three packages ngs, ncbi-vdb and sratools in ncbi. I followed the steps in instructions to install the packages again. I passed the ./configure step for sratools, but the make step encountered error which was also reported on the sratools page.
https://github.com/ncbi/sra-tools/issues/43?_pjax=%23js-repo-pjax-container

**Comment by vradore** [comment]
I probably solve the issue myself. I think the problem is the installation of sra-tools, having nothing to do with ncbi-vdb. What seems to have solved the issue was defining the ngs-sdk-prefix and ncbi-vdb-build directories at the ./configure step.

**Comment by klymenko** [comment]
What exact commands do you use to download/configure/build?

Do you have the same problems as in  https://github.com/ncbi/sra-tools/issues/43 ?
