### ISSUE TITLE
Change to 2.8.1 release tag / checksum error?

### ISSUE THREAD

**Issue by cmdcolin** [ncbi/ncbi-vdb#13]
Hello, I was wondering if there were any changes that caused version 2.8.1 to be retagged? There was a checksum error in a Homebrew package for sratoolkit and they were wondering if it was due to a release tag change and wanted to see if it could be confirmed https://github.com/Homebrew/homebrew-science/pull/4767

**Comment by klymenko** [comment]
Yes, there was a minor change and it 2.8.1 was retagged.

**Comment by cmdcolin** [comment]
Okay thanks for the confirmation!
