### ISSUE TITLE
Request: i386 support

### ISSUE THREAD

**Issue by ning-y** [ncbi/ncbi-vdb#146]
There appears to be no support for i386. Please consider adding support. Thank you!

```
+ make
mkdir -p /root/ncbi-outdir/ncbi-vdb/linux/gcc/i386/rel/obj
cd /root/ncbi-outdir/ncbi-vdb/linux/gcc/i386/rel/obj; cmake -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=/root/ncbi-outdir/ncbi-vdb/linux/gcc/i386/rel/ilib -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/root/ncbi-outdir/ncbi-vdb/linux/gcc/i386/rel/lib -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/root/ncbi-outdir/ncbi-vdb/linux/gcc/i386/rel/bin -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local/ncbi/ncbi-vdb -DINST_BINDIR=/usr/local/ncbi/ncbi-vdb/bin -DINST_LIBDIR=/usr/local/ncbi/ncbi-vdb/lib32 -DINST_INCDIR=/usr/local/ncbi/ncbi-vdb/include -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DPYTHON_PATH=/usr/bin/python3 -DRUN_SANITIZER_TESTS= -DRUN_SANITIZER_TESTS_OVERRIDE=  -DLIBS_ONLY=ON /ncbi-vdb
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
VERSION=3.1.0
CMake Error at build/env.cmake:105 (message):
  unknown architecture i686
Call Stack (most recent call first):
  CMakeLists.txt:78 (include)


-- Configuring incomplete, errors occurred!
See also "/root/ncbi-outdir/ncbi-vdb/linux/gcc/i386/rel/obj/CMakeFiles/CMakeOutput.log".
make: *** [/ncbi-vdb/build/Makefile.env:106: cmake_libs] Error 1
FATAL:   While performing build: while running engine: exit status 2
```

**Comment by ning-y** [comment]
Related: https://github.com/ncbi/ncbi-vdb/issues/8

My use case: I bought a old ThinkPad w/ i386. I use it as a server to download sequence data. I then transfer the sequence data to a HPC where it is analyzed. This roundabout download process is because the only internet-enabled node on the HPC is also the login node and also serves a web server, so the admin rightfully disallows large downloads on that login node. The transfer from my ThinkPad to HPC doesn't go through the login node, but a "transfer" node that is not internet-enabled.

**Comment by durbrow** [comment]
We do not have access to any 32-bit hardware to build and/or test. Even if you were to do the patches yourself, we would not be much help to you, since we wouldn't be able to build or test it. You would also need to build your own executables.

I'm sorry we can't be more helpful, but we are limited to the hardware and OS'es that our IT provides for us.

**Comment by ning-y** [comment]
@durbrow I understand! Was a bit of a long shot asking for 32-bit support in 2024. Thanks for the prompt response though!
