### ISSUE TITLE
`with-vdb explicitly specified, but not supported on this platform` error

### ISSUE THREAD

**Issue by kensully** [ncbi/ncbi-vdb#15]
I am on Ubuntu 16.04 32 bit platform. I am trying to build `gbench-2.12.0`. I ran `build-linux-distro.sh` 
I applied [this patch](https://anonscm.debian.org/cgit/debian-med/ncbi-vdb.git/tree/debian/patches/add_-msse2.patch) to bypass msse2 failure. It compiled and installed `ncbi-vdb` locally, and  the script went on but it failed with `with-vdb explicitly specified, but not supported on this platform` error in the final `/configure` process.  

I checked out the `configure` parameters. 

    ./configure --with-dll --with-mt --with-gbench --with-vdb=/home/***/GENOME/NCBI-TOOLS/gbench-src-2.12.0/ThirdParty/i386Release --without-debug --with-boost --with-libxml --with-libxslt --with-sqlite3 --with-lzo --with-ftgl --with-gnutls --with-wxwidgets=/home/***/GENOME/NCBI-TOOLS/gbench-src-2.12.0/ThirdParty/i386Release --with-wxwidgets-ucs --with-projects=scripts/projects/ncbi_gbench.lst --with-runpath=/opt/ncbi/gbench-2.12.0/lib --without-sybase --with-flat-makefile --without-caution

Why is it failing?
I hope you guide me.
Regards
Kenn

**Comment by kwrodarmer** [comment]
NCBI has made a choice to no longer provide engineering support for 32-bit platforms. Essentially we have no way of ensuring that the library will run or even build on 32-bit hardware.

I'm sorry for this, but in 2017 it is getting hard to find any hardware that isn't 64-bit...
