### ISSUE TITLE
Test for root in make install

### ISSUE THREAD

**Issue by sachalau** [ncbi/ncbi-vdb#17]
Hello,

We are getting errors on bioconda (https://github.com/bioconda/bioconda-recipes/pull/8525) because of the test for ROOT at the begining of build/Makefile.install.

The build is detected as being run by the root and it tries to link the libraries to a folder that does not existe. The faulting part is this one :

```
# set up installation locations

#fake root for debugging
#uncomment this line and change the following test for root ( see under install: ) to succeed:
#ROOT = ~/root
ifeq (linux, $(OS))
    ifeq (0, $(shell id -u))
        LINUX_ROOT = true
    endif
endif

ifeq (true, $(LINUX_ROOT))
    KONFIG_DIR = $(ROOT)/etc/ncbi
    INCLUDE_SYMLINK = $(ROOT)/usr/include/ncbi-vdb
    PROFILE_FILE = $(ROOT)/etc/profile.d/ncbi-vdb
else
    KONFIG_DIR = $(LIB_TARGET)/ncbi
endif
```

It says it's only for debugging and we should change the test. However this is not convinient because it means we have to patch the file in the bioconda build.

Do you think we could get a fix on this ? I could submit a PR but I'm not sure what should be done.

(there is the exact same problem in `ngs-tools`)

**Comment by klymenko** [comment]
What errors do you get?
Do you have an environment variable ROOT defined when you run "make install"?

**Comment by sachalau** [comment]
Here is the associated PR in bioconda, sorry I should have linked it before : 

https://github.com/bioconda/bioconda-recipes/pull/8525

We get this error : 

ln: creating symbolic link `/opt/conda/usr/include/ncbi-vdb': No such file or directory

Because we are building by default in another folder (see https://circleci.com/gh/bioconda/bioconda-recipes/7806?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Comment by kwrodarmer** [comment]
Ah, just left you a message in your issue 8525.

There is the issue of where you build, which is an output directory, and the issue of where you install. Our use of a ROOT (file-system root, that is) environment variable in this script is there only for us, and not as a general control. We have to use it to simulate root access because on Federal computers we cannot ever have root access. It is not meant to be a means of selecting a different build directory.

**Comment by klymenko** [comment]
@sachalau , this issue should be fixed by now.
Please confirm.
