### ISSUE TITLE
Some builtins that vdb uses are gcc-specific and don't compile with clang.

### ISSUE THREAD

**Issue by yurivict** [ncbi/ncbi-vdb#18]
For example, ```__builtin_ia32_shufps``` and ```__builtin_ia32_shufpd``` are gcc-specific.

You should replace them with primitives, ```_mm_shuffle_ps``` and ```_mm_shuffle_pd```, or better yet, you can use the SIMD library instead, like libsimdpp: https://github.com/p12tic/libsimdpp

**Comment by klymenko** [comment]
@yurivict, is this still an issue?
