### ISSUE TITLE
hdf5 not recognized on Arch

### ISSUE THREAD

**Issue by MatthewRalston** [ncbi/ncbi-vdb#22]
Arch linux 5.3.6-arch1

hdf5-1.10.5-1
gcc/g++ 9.2.0
clang 9.0.0

Hello, I have libhdf5 shared objects, C++ files etc in `/usr/lib` and headers in `/usr/include`

```bash
>ls /usr/include/hdf5
hdf5.h hdf5_hl.h hdf5.mod
>ls /usr/include/libhdf5 # symlinks to the above
libhdf5.h libhdf5_hl.h libhdf5.mod
```

**Comment by kwrodarmer** [comment]
Again, we have no means of supporting arch-linux, meaning that while we will do what we can to be as portable as possible, you're sort of on your own with distros that we do not or cannot test within the US Federal Government.

If you think you have a fix that is portable, by all means let us know.

**Comment by Piezoid** [comment]
The compile-check with arguments `-Wl,-Bstatic -lhdf5 -Wl,-Bdynamic -ldl -lm -lz` fails because Arch-linux does not ship static libraries.

The changelog for 2.9.0 says this is deliberate:
> **build**: recognize version of libhdf5 that does not allow static linking and do not try to use it

**Comment by kwrodarmer** [comment]
Regarding HDF5 - the fix you might pursue is the one that we will be applying which is to remove the tool that uses HDF5 from the build.

**Comment by MatthewRalston** [comment]
I'll consider the suggestion. If I knew how to install the non-static (dynamic?) libraries then I would just try that
