### ISSUE TITLE
VCursorCellDataDirect returns a zero length read ... but shouldn't?

### ISSUE THREAD

**Issue by jgans** [ncbi/ncbi-vdb#24]
I am using VCursorCellDataDirect to stream sequence data from SRA files into my application. In general, this works fine. However, I have run across an SRA record for which the API call:
`VCursorCellDataDirect(cur, index, read_col_id, &elem_bits, (const void **)&str.addr, &boff, &str.len )` successfully returns, and sets the `str.len` value to zero. 

A subsequent call to `VCursorCellDataDirect( cur, index, read_len_col_id, &elem_bits, (const void **)&read_len_array, &boff, &num_read_len )` successfully returns with `num_read_len` equal to 2 and `read_len_array[0]=74` and `read_len_array[1]=74`.

Here is my question -- if the returned string length is zero in the first call to `VCursorCellDataDirect`, is it an error to attempt to load the read length array for the same read index? I'm not sure why the sum of the read length array elements aren't zero (for consistency). The SRA record in question is SRR1614306.

**Comment by kwrodarmer** [comment]
I assume you're reading a SEQUENCE table and the READ column, presumably typed to textual representation. It would indeed be an error for the read column to return 0 bases while the read lengths appear to sum to 148.

Let us investigate! Thanks.

**Comment by jgans** [comment]
I can download the SRA file for SRR1614306 using `prefetch`:
```
ls SRR1614306/
CM000663.1	CM000668.1	CM000673.1	CM000678.1	CM000683.1	SRR1614306/
CM000664.1	CM000669.1	CM000674.1	CM000679.1	CM000684.1
CM000665.1	CM000670.1	CM000675.1	CM000680.1	CM000685.1
CM000666.1	CM000671.1	CM000676.1	CM000681.1	CM000686.1
CM000667.1	CM000672.1	CM000677.1	CM000682.1	NC_012920.1
```
However, when I run `fasterq-dump` on this record, it throws the error:

```
fasterq-dump SRR1614306
2020-05-06T15:07:52 fasterq-dump.2.10.0 fatal: SIGNAL - Segmentation fault 
```
Could there be a problem with this particular record?

**Comment by kwrodarmer** [comment]
It very well could be a problem with the run. We are looking at it.

To be sure we are seeing the same thing as you, would you minding telling us which row is giving you this behavior? And if it's multiple rows, just a handful for testing? Thanks a lot!

**Comment by jgans** [comment]
The read when the error manifests appears to be random. However, looking more closely at sra-tools/tools/fastq_iter.c:
```
 if ( rc1 == 0 && self -> opt . with_read_len )
        {
            uint32_t sum_read_len = 0;
            uint32_t i;
            for ( i = 0; i < rec -> num_read_len; ++i )
                sum_read_len += rec -> read_len[ i ];
            if ( rec -> read . len != sum_read_len )
            {
                rec -> read . len  = sum_read_len;
                rec -> read . size = sum_read_len;

                rc1 = read_bounded_quality_fix( self -> cmn, self -> quality_id,
                                &( self -> qual_buffer ),
                                &( self -> qual_2_ascii[ 0 ] ),
                                &( rec -> quality ),
                                sum_read_len );             
            }
        }
```
it appears that that I can simply stop testing for `rec -> read . len != sum_read_len` (as I don't currently need the quality scores). I am already using the `read_len` array to extract the individual read lengths. Is this a viable approach?

**Comment by klymenko** [comment]
Could you try our latest 2.11.0. release?
