### ISSUE TITLE
installation does not include files required by sra-tools

### ISSUE THREAD

**Issue by rekado** [ncbi/ncbi-vdb#3]
sra-tools depends on headers and files in the `ilib` directory that are not included in the installation output.

See https://github.com/ncbi/sra-tools/issues/11

**Comment by kwrodarmer** [comment]
sra-tools used to be in the same project as ncbi-vdb. It was split off when we introduced the ngs API.

To address this issue we will make one library (kapp) that was always considered internal to the tools but dependent upon ncbi-vdb into an installed library, even though it is only useful to sra-tools.

**Comment by rekado** [comment]
In my [packages for GNU Guix](http://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/bioinformatics.scm#n1388) I have temporarily solved this by letting ncbi-vdb install kdf5, as well as copy all ilibs and headers to expected locations in the output directory where they can be found by the configuration script of sra-tools.
