### ISSUE TITLE
Benchmarking parallel SRA downloads using prefetch on AWS

### ISSUE THREAD

**Issue by jgans** [ncbi/ncbi-vdb#30]
Since the question of downloading SRA runs in "parallel" using many cloud instances to run prefetch, I though I would share the following "pseudo-benchmark" results. 

<img width="437" alt="image" src="https://user-images.githubusercontent.com/36452131/85181769-fc14dc80-b243-11ea-96b5-87cec6086887.png">

The x-axis shows the number of single core, 25GB/s AWS instances (c5n.large) and the y-axis shows the fraction of the downloads that were successful. Data was collected on June 19, starting at 12 noon MT.

This is a "pseudo" benchmark because it does not attempt to download the exact same set of SRA accessions, but instead downloads different SRA accessions that have very similar file sizes (I am searching a list of ~250K SRA accessions that have been sorted in order of number of bases).

**Comment by kwrodarmer** [comment]
Thank you, this is great information! Wow!
