### ISSUE TITLE
Any documentation?

### ISSUE THREAD

**Issue by eiva** [ncbi/ncbi-vdb#5]
How to create schema?
Any notes on folder structure?
How to define indexes?

**Comment by kwrodarmer** [comment]
We have not yet published formal documentation on schema creation, but will create a ticket for doing so.

The directory structure is a wider topic, and there are some slides that may be found at [NCBI](http://www.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=doc) that show some details of internal structure of many SRA objects.

So we will address your questions with some online documentation. Thanks for asking, and stay tuned.
