### ISSUE TITLE
-bash: vdb-config: command not found

### ISSUE THREAD

**Issue by akjr123** [ncbi/ncbi-vdb#51]
Hello. After cd into bin, and trying to execute vdb-config, vdb-config -i --interactive-mode textual, and vdb-config --restore-defaults, with and without ./, and ./[command].sh, I am always receiving the following errors:

-bash: vdb-config: command not found
or
-bash: ./vdb-config: cannot execute binary file: Exec format error

How do I overcome this error?
This is after downloading the sratoolkit.3.0.0-mac64.

**Comment by akjr123** [comment]
This is after downloading the sratoolkit.3.0.0-mac64.

**Comment by klymenko** [comment]
`vdb-config` is located in directory `bin` of `sratoolkit.3.0.0-mac64`
