### ISSUE TITLE
Build system doesn't find cmake3 on CentOS 7

### ISSUE THREAD

**Issue by alanorth** [ncbi/ncbi-vdb#52]
CentOS 7 has both `cmake` version 2.8.x and `cmake3` version 3.17.x available in the system packages. The build system fails because it only finds the older cmake:

```
CMake Error at CMakeLists.txt:52 (cmake_minimum_required):
  CMake 3.16 or higher is required.  You are running version 2.8.12.2
```

Other than hacky solutions like removing the system's cmake 2.8.x and symlinking cmake to the cmake3 binary, how can I tell the build system where to find cmake3?

**Comment by alanorth** [comment]
I was able to get this to compile by replacing references to `cmake` and `ctest` with `cmake3` and `ctest3` in `build/Makefile.env`.

**Comment by aboshkin** [comment]
@alanorth, we will add the ability to override the cmake command in our next release. Thank you for reporting this!
