### ISSUE TITLE
Unable to stream SRR12596531 but can read from local disk

### ISSUE THREAD

**Issue by jgans** [ncbi/ncbi-vdb#58]
I would like to read all SRA records using AWS instances that do not have any local storage. To this end, I would like to stream the contents of each SRA record directly from its home in AWS S3 to my application using the NCBI SRA C++ API (e.g., `ngs::ReadIterator`). 

In general, this works well. However, when testing my algorithm against some of the largest SRA records, the following error is reproducibly encountered when streaming SRR12596531 after reading about 5.7% of the spots:

`VCursorCellDataDirect failed: '(INSDC:dna:text)READ' [188973057] rc = RC(rcXF,rcFunction,rcExecuting,rcParam,rcBadVersion)` 

This same SRA record (SRR12596531) can be read from local storage (after downloading with `prefetch`) without any error. 

While the above mentioned error is being generated by `unzip_func()` in `ncbi_vdb/libs/vxf/unzip.c` I suspect that the error is caused by passing invalid `VBlobHeader` information to the unzip function. Any suggestions for tracking down this issue would be appreciated! The use of functions that are assigned at run-time makes the code very difficult to read. Is there a way to output a human-readable function call stack when an error is encountered?

**Comment by kwrodarmer** [comment]
Hi @jgans!

VDB version 2 assumes some level of random access. Even in streaming mode it still is fetching the remote file and writing it to temporary random-access media to perform its operations. The behavior you describe would be consistent with running out of local POSIX disk space during the operation. You might experiment with a larger allocation and see if that gives better behavior.

**Comment by klymenko** [comment]
Try to set TMPDIR=location

**Comment by jgans** [comment]
By default, it appears that an anonymous file is created in `/tmp` (when `TMPDIR` is unset). When the `vdb-config` tool is used to disable file caching (by unchecking the `enable local file caching` under `CACHE`), the anonymous file is no longer created. Instead, system RAM is consumed, but only up to the limit (1 GB) that was specified with `vdb-config` (in `RAM used` under `CACHE`). Nice! As an added bonus, the streaming speed for the c5a.large EC2 instance appears to be slightly faster when using the RAM-based cache.

I realize that the RAM-based cache may run into trouble when downloading reference sequences for aligned reads (I plan to test soon). This may require using EC2 instances will local store to enable robust caching.

The
