### ISSUE TITLE
Error: `pshufb' is not supported on `generic64.aes'

### ISSUE THREAD

**Issue by tseemann** [ncbi/ncbi-vdb#6]
I got the this assembler error. I have modern Haswell CPU.

```
016-08-21 11:20:37 +1000

make
install

Checking make status of object libraries...
gcc -c   -DNDEBUG -m64   -DLINUX -DUNIX -D_GNU_SOURCE -D_REENTRANT -D_FILE_OFFSET_BITS=64 -DPKGNAME=linux64 -D_ARCH_BITS
=__SIZEOF_POINTER__*__CHAR_BIT__ -DLIBPREFIX=lib -DSHLIBEXT=so  -I/tmp/sratoolkit--ncbi-vdb-20160821-45016-1l3jwn7/ncbi-
vdb-2.7.0/interfaces/override -I/tmp/sratoolkit--ncbi-vdb-20160821-45016-1l3jwn7/ncbi-vdb-2.7.0/libs/krypto/linux -I/tmp
/sratoolkit--ncbi-vdb-20160821-45016-1l3jwn7/ncbi-vdb-2.7.0/libs/krypto/unix -I/tmp/sratoolkit--ncbi-vdb-20160821-45016-
1l3jwn7/ncbi-vdb-2.7.0/libs/krypto -I/tmp/sratoolkit--ncbi-vdb-20160821-45016-1l3jwn7/ncbi-vdb-2.7.0/interfaces -I/tmp/s
ratoolkit--ncbi-vdb-20160821-45016-1l3jwn7/ncbi-vdb-2.7.0/interfaces/cc/gcc/x86_64 -I/tmp/sratoolkit--ncbi-vdb-20160821-
45016-1l3jwn7/ncbi-vdb-2.7.0/interfaces/cc/gcc -I/tmp/sratoolkit--ncbi-vdb-20160821-45016-1l3jwn7/ncbi-vdb-2.7.0/interfa
ces/os/linux -I/tmp/sratoolkit--ncbi-vdb-20160821-45016-1l3jwn7/ncbi-vdb-2.7.0/interfaces/os/unix -I/tmp/sratoolkit--ncb
i-vdb-20160821-45016-1l3jwn7/ncbi-vdb-2.7.0/interfaces/ext -I/home/linuxbrew/.linuxbrew/Cellar/sratoolkit/2.7.0/include
-I. -MD -o aes-ncbi.aes-ni.pic.o -fPIC -O3 -Wno-variadic-macros -fno-strict-aliasing -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE
=1 -Wall -D_LIBRARY -DUSEVEC -DUSEVECREG -DUSEAESNI -funsafe-math-optimizations -mmmx -msse -msse2 -msse3 -mssse3 -msse4
.1 -maes -Wa,-march=generic64+aes -Wa,-ahlms=/tmp/sratoolkit--ncbi-vdb-20160821-45016-1l3jwn7/ncbi-vdb-2.7.0/libs/krypto
/aes-ncbi.aes-ni.pic.o.list /tmp/sratoolkit--ncbi-vdb-20160821-45016-1l3jwn7/ncbi-vdb-2.7.0/libs/krypto/aes-ncbi.c
/tmp/sratoolkit--ncbi-vdb-20160821-45016-1l3jwn7/ncbi-vdb-2.7.0/libs/krypto/aes-ncbi.c: In function 'KAESBlockCipherVecA
esNiMake':
/tmp/sratoolkit--ncbi-vdb-20160821-45016-1l3jwn7/ncbi-vdb-2.7.0/libs/krypto/aes-ncbi.c:2507:34: warning: 'd' may be used
 uninitialized in this function [-Wmaybe-uninitialized]
     uint32_t level = 1, a, b, c, d;
/tmp/sratoolkit--ncbi-vdb-20160821-45016-1l3jwn7/ncbi-vdb-2.7.0/libs/krypto/aes-ncbi.c:2507:31: warning: 'c' may be used
 uninitialized in this function [-Wmaybe-uninitialized]
     uint32_t level = 1, a, b, c, d;
                               ^
/tmp/cc104hCB.s: Assembler messages:
/tmp/cc104hCB.s:95: Error: `pshufb' is not supported on `generic64.aes'
/tmp/cc104hCB.s:99: Error: `pshufb' is not supported on `generic64.aes'
/tmp/cc104hCB.s:103: Error: `pshufb' is not supported on `generic64.aes'
/tmp/cc104hCB.s:111: Error: `pshufb' is not supported on `generic64.aes'
/tmp/cc104hCB.s:114: Error: `pshufb' is not supported on `generic64.aes'
/tmp/cc104hCB.s:117: Error: `pshufb' is not supported on `generic64.aes'
/tmp/cc104hCB.s:125: Error: `pshufb' is not supported on `generic64.aes'
/tmp/cc104hCB.s:128: Error: `pshufb' is not supported on `generic64.aes'
/tmp/cc104hCB.s:131: Error: `pshufb' is not supported on `generic64.aes'

make[4]: *** [aes-ncbi.aes-ni.pic.o] Error 1
reattempting without AES-NI instructions
Installing libraries to /home/linuxbrew/.linuxbrew/Cellar/sratoolkit/2.7.0/lib64
installing 'libncbi-vdb.a.2.7.0'... success
installing 'libncbi-vdb.so.2.7.0'... success
installing 'libncbi-wvdb.a.2.7.0'... success
installing 'libncbi-wvdb.so.2.7.0'... success
installing 'libncbi-ngs-c++.a.2.7.0'... success
Installing includes to /home/linuxbrew/.linuxbrew/Cellar/sratoolkit/2.7.0/include
Installing configuration files to /home/linuxbrew/.linuxbrew/Cellar/sratoolkit/2.7.0/lib64/ncbi/
Please add /home/linuxbrew/.linuxbrew/Cellar/sratoolkit/2.7.0/lib64 to your LD_LIBRARY_PATH, e.g.:
      export LD_LIBRARY_PATH=/home/linuxbrew/.linuxbrew/Cellar/sratoolkit/2.7.0/lib64:$LD_LIBRARY_PATH
Use /home/linuxbrew/.linuxbrew/Cellar/sratoolkit/2.7.0/lib64 in your link commands, e.g.:
      export NCBI_VDB_LIBDIR=/home/linuxbrew/.linuxbrew/Cellar/sratoolkit/2.7.0/lib64
      ld -L$NCBI_VDB_LIBDIR -lncbi-vdb ...

```

My CPU flags:

```
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc
```

**Comment by kwrodarmer** [comment]
Hi @tseemann ,
What version of gcc are you running?

**Comment by tseemann** [comment]
@kwrodarmer  `gcc (Homebrew gcc 5.3.0) 5.3.0`

**Comment by kwrodarmer** [comment]
This is not an error we have seen, heard of, or been able to reproduce yet. You see we tell gcc `-mmmx -msse -msse2 -msse3 -mssse3 -msse4`. And the code in question has not changed for a very long time. We'll try it with a build of 5.3.0.

**Comment by tseemann** [comment]
@kwrodarmer thanks - i'd be interested in what you find!

**Comment by kwrodarmer** [comment]
Incidentally, we build with 5.4.0 and there are no problems. At this point, there is no evidence that there is anything in our code that could cause this issue. Obviously, `pshufb` is a legitimate instruction and every compiler we've encountered other than very old ones compiles the code without problem.

**Comment by tseemann** [comment]
I believe that if you have an older Intel CPU, then it will cause this error irrespective of GCC. If `-march=core2` then it will be capped at `-msse2` and won't have the `pshufb` instruction?

**Comment by sjackman** [comment]
`Error: `pshufb' is not supported on `generic64.aes'`
As this error is coming from the assembler (not the compiler), it's possible that the assembler version is too old. To troubleshoot, try `as --version` and `brew list --versions binutils`

**Comment by kwrodarmer** [comment]
We've not had any luck reproducing the error, so we need to go on your results. Let us know what you find.

**Comment by qiaowei-vvjoe** [comment]
Hi 
I guess I got the same error as you,but after read the issue I still don't know how to fix it.Could you please give me a help?Thanks so much in advance.

$ make install
Checking make status of object libraries...
NOTE - internal library libkff cannot be built: It requires 'libmagic' and its development headers.
gcc -c  -std=gnu11  -DNDEBUG -m64   -DLINUX -DUNIX -D_GNU_SOURCE -D_REENTRANT -D_FILE_OFFSET_BITS=64 -DPKGNAME=linux64 -D_ARCH_BITS=__SIZEOF_POINTER__*__CHAR_BIT__ -DLIBPREFIX=lib -DSHLIBEXT=so  -I/mnt/disk1/qiaowei/ncbi/ncbi-vdb/interfaces/override -I/mnt/disk1/qiaowei/ncbi/ncbi-vdb/libs/krypto/linux -I/mnt/disk1/qiaowei/ncbi/ncbi-vdb/libs/krypto/unix -I/mnt/disk1/qiaowei/ncbi/ncbi-vdb/libs/krypto -I/mnt/disk1/qiaowei/ncbi/ncbi-vdb/interfaces -I/mnt/disk1/qiaowei/ncbi/ncbi-vdb/interfaces/cc/gcc/x86_64 -I/mnt/disk1/qiaowei/ncbi/ncbi-vdb/interfaces/cc/gcc -I/mnt/disk1/qiaowei/ncbi/ncbi-vdb/interfaces/os/linux -I/mnt/disk1/qiaowei/ncbi/ncbi-vdb/interfaces/os/unix -I/mnt/disk1/qiaowei/ncbi/ncbi-vdb/interfaces/ext -I/mnt/disk1/qiaowei/ncbi/ngs/ngs-sdk -I. -MD -o aes-ncbi.aes-ni.pic.o -fPIC -O3 -Wno-variadic-macros -fno-strict-aliasing -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -fstack-protector -Wa,--noexecstack -Wall -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-c++11-extensions -D_LIBRARY -DUSEVEC -DUSEVECREG -DUSEAESNI -funsafe-math-optimizations -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -maes -Wa,-march=generic64+aes -Wa,-ahlms=/mnt/disk1/qiaowei/ncbi/ncbi-vdb/libs/krypto/aes-ncbi.aes-ni.pic.o.list /mnt/disk1/qiaowei/ncbi/ncbi-vdb/libs/krypto/aes-ncbi.c
/mnt/disk1/qiaowei/ncbi/ncbi-vdb/libs/krypto/aes-ncbi.c: In function ‘KAESBlockCipherVecAesNiMake’:
/mnt/disk1/qiaowei/ncbi/ncbi-vdb/libs/krypto/aes-ncbi.c:2507:34: warning: ‘d’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     uint32_t level = 1, a, b, c, d;
                                  ^
/mnt/disk1/qiaowei/ncbi/ncbi-vdb/libs/krypto/aes-ncbi.c:2507:31: warning: ‘c’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     uint32_t level = 1, a, b, c, d;
                               ^
/mnt/disk1/qiaowei/ncbi/ncbi-vdb/libs/krypto/aes-ncbi.c: At top level:
cc1: warning: unrecognized command line option "-Wno-c++11-extensions" [enabled by default]
cc1: warning: unrecognized command line option "-Wno-c++98-compat-pedantic" [enabled by default]
cc1: warning: unrecognized command line option "-Wno-c++98-compat" [enabled by default]
/tmp/ccuG9Snw.s: Assembler messages:
/tmp/ccuG9Snw.s:83: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:87: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:91: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:95: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:99: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:103: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:108: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:112: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:116: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:121: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:125: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:129: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:134: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:138: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:142: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:147: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:151: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:155: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:160: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:164: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:168: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:173: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:177: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:181: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:186: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:190: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:194: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:199: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:203: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:205: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:233: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:239: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:243: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:244: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:247: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:251: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:257: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:261: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:266: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:270: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:274: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:279: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:283: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:287: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:292: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:296: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:300: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:305: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:309: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:313: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:318: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:322: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:326: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:331: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:335: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:339: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:344: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:348: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:352: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:357: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:361: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:365: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:370: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:374: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:378: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:383: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:388: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:393: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:397: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:421: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:425: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:429: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:433: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:435: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:437: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:441: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:450: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:454: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:455: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:461: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:463: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:467: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:474: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:479: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:483: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:488: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:492: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:496: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:497: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:501: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:510: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:511: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:516: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:521: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:526: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:531: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:535: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:540: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:544: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:548: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:549: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:553: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:562: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:563: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:568: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:573: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:578: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:582: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:587: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:588: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:592: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:598: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:608: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:612: Error: `pshufb' is not supported on `generic64.aes'
/tmp/ccuG9Snw.s:616: Error: `pshufb' is not supported on `generic64.aes'
make[4]: *** [aes-ncbi.aes-ni.pic.o] Error 1
reattempting without AES-NI instructions
NOTE - library libkdf5 cannot be built: It requires 'libhdf5' and its development headers.
mkdir: cannot create directory ‘/usr/local/ncbi’: Permission denied
make[1]: *** [/usr/local/ncbi/ncbi-vdb/lib64] Error 1
make: *** [install] Error 2

**Comment by jdmontenegro** [comment]
Hi all,
I am getting the same error trying to compile ngs-vdb. I didnt see any errors during config or after make. The error only appeared after "make install". Any advice would be very welcome.

Regards,

**Comment by tseemann** [comment]
@jdmontenegro i think @sjackman solved this issue but the authors might have missed it?
```
Try removing -Wa,-march=generic64+aes from the compiler command line. The compiler should know which architecture option to pass to the assembler.
```
