### ISSUE TITLE
Is there a way to force the release of the VDB memory cache with C++ SDK?

### ISSUE THREAD

**Issue by jgans** [ncbi/ncbi-vdb#60]
As a follow on to a previous [issue](https://github.com/ncbi/ncbi-vdb/issues/58) related to the memory/disk cache that is maintained by the VDB library: is there a way to free the VDB memory cache when it is no longer needed? 

My application first streams SRA data and then performs follow on (and potentially memory intensive) processing steps. I was hoping that deleting the `ngs::ReadCollection` object would free any associated memory cache, but this does not appear to be the case.

**Comment by kwrodarmer** [comment]
I believe that releasing the `ngs::ReadCollection` should reclaim the memory. It would not if there were other outstanding objects.

**Comment by kwrodarmer** [comment]
NGS uses VDB. VDB caches open ReadCollections (runs) such that if they are opened multiple times across different threads, they will access the same object. This object is a file, in your case a file in the temporary filesystem. It is populated by retrieving data from a remote server.

If any other ReadCollection were to be instantiated for the same run, it would attach a reference to the underlying file. When the last ReadCollection goes out of scope, it should release the underlying VDB structures - including this temporary file. When the file is released, it should be removed from cache and deleted from the filesystem.

If you are not seeing the file reclaimed in the filesystem, it points to an outstanding reference somewhere. The VDB team will be able to diagnose the issue.
