### ISSUE TITLE
Enable Apple Silicon builds by adding `interfaces/cc/clang/aarch64`

### ISSUE THREAD

**Issue by cho-m** [ncbi/ncbi-vdb#65]
In Homebrew, I was able to build v3.0.0 on Apple Silicon by adding an `interfaces/cc/clang/aarch64` (https://github.com/Homebrew/homebrew-core/pull/98654) linked from existing `interfaces/cc/gcc/arm64`

I will note that trying to build with GCC failed since `ARCH=aarch64` rather than `arm64`, so build was looking for `interfaces/cc/gcc/aarch64`, which doesn't exist.

https://github.com/ncbi/ncbi-vdb/blob/34c611317dbe2832cf24ec543a95e9ca7b9eb2e6/build/env.cmake#L68-L71

**Comment by klymenko** [comment]
Could you try it again with our latest code?

**Comment by timsutton** [comment]
Confirmed, this now builds successfully!
