### ISSUE TITLE
bitcpy

### ISSUE THREAD

**Issue by HuangseYuanli** [ncbi/ncbi-vdb#70]
”bitcpy“ in data-buffer.c is undefine,how to solve this problem? Thank you!
Error reporting prompt：
/usr/local/sratool/ncbi-vdb-3.0.0/libs/klib/data-buffer.c:688: undefined reference to `bitcpy'

**Comment by durbrow** [comment]
What are you building on? There are some problems with ARM + clang. There's a missing directory, you can fix it by copying the `arm64` directory from `interfaces/cc/gcc` to `interfaces/cc/clang`
