### ISSUE TITLE
modify the compiler

### ISSUE THREAD

**Issue by HuangseYuanli** [ncbi/ncbi-vdb#73]
Hello, how can I modify the compiler.When I use: ./configure cc=clang cxx=clang++, gcc is not modified to clang

**Comment by luketian09** [comment]
I also encountered the same problem.
When I passed ./configure CC=clang CXX=clang++, I found that only the parameters of CPP were modified, and CC was still equal to gcc -c
How should I compile with clang?

**Comment by klymenko** [comment]
This possibility is not implemented yet.

**Comment by HuangseYuanli** [comment]
Oh, I see. thank you.
