### ISSUE TITLE
When compiling SRA Tools & NCBI VDB in fedora36 environment, HDF5 static library or shared library file cannot be found

### ISSUE THREAD

**Issue by HuangseYuanli** [ncbi/ncbi-vdb#76]
When I was configuring, the following problems occurred:
checking for fuse library... yes
checking for hdf5 library... no
checking for magic library... yes
checking for xml2 library... yes

In the konfigure.perl file, I see the following:
$library = '-Wl,-Bstatic -lhdf5 -Wl,-Bdynamic -ldl -lm -lz'
The explanation given is:build: recognize version oflibhdf5 that does not allow static linking and donot try to use it.

What I want to know is whether HDF5 will continue to be supported in version 3.0.0. If so, what should I do next?
After searching for relevant information, bioconda provides a solution:
.- setup/ konfigure.perl+++ setup/ konfigure.perl@-1654,7 +1654, 7 @R
$flags = $n;$log = "
int main( ) {
}ln'
}elsif (n eq " hdf5 ' ) {
$library = '-wl,-Bstatic -lhdf5 -wl,-Bdynamic -ldl -lm -lz ';$library = '-wl，-Bdynamic -lhdf5 -ldl -lm -lz';
$log = "#include <hdf5.h> in int main( ) { H5close
(; }n"
}elsif ($n eq 'fuse ' ) i
sflags = '-D_FILE_OFFSET_BITS=64' ;
--- tools/ pacbio-load/Makefile
+++ tools/pacbio-load/Makefilee-105,9 +105,9 @@
-stk-version :-skdf5 l
-sload \-shdf5 v-lhdf5 v
-sncbi-wvdb l-sm l
-lm v
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/sra-tools/0001-No-libhdf5-libxml2-static-link-sra-tools.patch
I hope to get an accurate plan, and I expect that the premise of using HDF5 is to respect the development direction of the community

**Comment by durbrow** [comment]
Having HDF5 enables functionality that is used internally at NCBI for processing HDF5 data files that are occasionally sent to us. It is not needed for reading SRA datasets.

The bioconda package was not created by us and is not maintained by us.
